### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by iampeterbanjo** [lillefp/cfp#9]
I came across this project while searching for issues tagged with hacktoberfest and language type Elixir. From reading the REAME.md it seems unclear what the purpose of this project is. What does "Cfp" stand for? Why are you working on Slack integration? Etc

I think updating the README will help others get involved with your project :)

**Comment by xvw** [comment]
You're absolutely right, but this project is in early-early stage of developement, and I have add the label "hacktoberfeest" to push my collaborators to the contribution.
